# docker-compose for debugging with vscode
version: '3'
services:
  minio:
    extends:
      file: ../local-dev.yml
      service: minio
  postgis:
    extends:
      file: ../local-dev.yml
      service: postgis
  pgbouncer:
    extends:
      file: ../local-dev.yml
      service: pgbouncer
  rabbitmq:
    extends:
      file: ../local-dev.yml
      service: rabbitmq
  solr:
    extends:
      file: ../local-dev.yml
      service: solr
    volumes:
      - "..:/hydroshare"
      - "solr_data_vol:/opt/solr/server/solr"
  hydroshare:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: hydroshare
    hostname: hydroshare
    devices:
      - "/dev/fuse"
    privileged: true
    environment:
      POSTGIS_HOST: postgis
      POSTGIS_PORT: 5432
      POSTGIS_PASSWORD: postgres
      POSTGIS_DB: postgres
      POSTGIS_USER: postgres
      PGPASSWORD: postgres
      RABBITMQ_PORT_5672_TCP_ADDR: rabbitmq
      SOLR_PORT_8983_TCP_ADDR: solr
      SOLR_HOST: solr
      TMP: /hs_tmp
      POSTGIS_PORT_5432_TCP_ADDR: postgis
      HS_PATH: ${PWD}
      PYTHONPATH: /hydroshare
      DJANGO_SETTINGS_MODULE: hydroshare.settings
    volumes:
      # hydroshare repository
      - "..:/hydroshare"
      # shared location for gunicorn.sock between containers
      - "temp_vol:/hs_tmp"
      # temp directory shared with celery workers
      - "share_vol:/shared_tmp"
    ports:
      - "1338:2022"
      - "8000:8000"
      - "5678:5678"
    links:
      - postgis:postgis
      - solr:solr
      - rabbitmq:rabbitmq
      - minio:minio
    depends_on:
      - postgis
      - solr
      - rabbitmq
      - minio
    stdin_open: true
    tty: true
    command: /bin/bash .vscode/init-hydroshare-debug
  defaultworker:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: defaultworker
    hostname: defaultworker
    environment:
      POSTGIS_HOST: postgis
      POSTGIS_PORT: 5432
      POSTGIS_PASSWORD: postgres
      POSTGIS_DB: postgres
      PGPASSWORD: postgres
      C_FORCE_ROOT: 1
      RABBITMQ_PORT_5672_TCP_ADDR: rabbitmq
      SOLR_PORT_8983_TCP_ADDR: solr
      SOLR_HOST: solr
      POSTGIS_PORT_5432_TCP_ADDR: postgis
      HS_PATH: ${PWD}
      PYTHONPATH: /hydroshare
      DJANGO_SETTINGS_MODULE: hydroshare.settings
      COLUMNS: 80
    ports:
      - "5555:5555"
    volumes:
      - "..:/hydroshare"
    links:
      - postgis:postgis
      - rabbitmq:rabbitmq
      - minio:minio
    depends_on:
      - hydroshare
      - postgis
      - solr
      - rabbitmq
      - minio
    stdin_open: true
    tty: true
    command: /bin/bash init-defaultworker
  companion:
    extends:
      file: ../local-dev.yml
      service: companion
  redis:
    extends:
      file: ../local-dev.yml
      service: redis
  nginx:
    extends:
      file: ../local-dev.yml
      service: nginx

volumes:
  postgis_data_vol:
  solr_data_vol:
  temp_vol:
  share_vol:
  rabbitmq_data_vol:
  minio_data_vol:
  redis_data_vol:
  companion_vol:
